/*-
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Copyright (c) 2019-2024 Hiroki Sato <hrs@FreeBSD.org>
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 */
/* Supported xHC PCI configurations */
#define XHC_CLASSC		0x0c0330ULL
#define XHC_VEN_INTEL		0x8086ULL

#define	XHC_DEV_COMET_LAKE_LP	0x02edULL
#define	XHC_DEV_COMET_LAKE	0x06edULL
#define	XHC_DEV_N2000		0x0f35ULL
#define	XHC_DEV_C3000		0x19d0ULL
#define	XHC_DEV_C210		0x1e31ULL
#define	XHC_DEV_E8000		0x22b5ULL
#define	XHC_DEV_PUMA		0x2bb5ULL
#define	XHC_DEV_CELERON		0x31a8ULL
#define	XHC_DEV_ICE_LAKE	0x34edULL
#define	XHC_DEV_TIGER_LAKE_H	0x43edULL
#define	XHC_DEV_N3350		0x5aa8ULL
#define	XHC_DEV_C220		0x8c31ULL
#define	XHC_DEV_NINE		0x8cb1ULL
#define	XHC_DEV_C610		0x8d31ULL
#define	XHC_DEV_EIGHT		0x9c31ULL
#define	XHC_DEV_WILDCAT_POINT	0x9cb1ULL
#define	XHC_DEV_SUNRISE_POINT	0x9d2fULL
#define	XHC_DEV_CANNON_POINT	0x9dedULL
#define	XHC_DEV_SILVER		0x31a8ULL
#define	XHC_DEV_TIGER_LAKE	0xa0edULL
#define	XHC_DEV_C230		0xa12fULL
#define	XHC_DEV_C620		0xa1afULL
#define	XHC_DEV_Z370		0xa2afULL
#define	XHC_DEV_CANNON_LAKE	0xa36dULL

#define XHC_VEN_AMD		0x1022ULL

#define	XHC_DEV_KERNCZ		0x145cULL
#define	XHC_DEV_STARSHIP	0x148cULL
#define	XHC_DEV_MATISSE		0x149cULL
#define	XHC_DEV_X399		0x43baULL
#define	XHC_DEV_X370		0x43b9ULL
#define	XHC_DEV_B350		0x43bbULL
#define	XHC_DEV_400		0x43d5ULL
#define	XHC_DEV_FCH_1		0x7812ULL
#define	XHC_DEV_FCH_2		0x7814ULL
#define	XHC_DEV_FCH_3		0x7914ULL

#define XHC_VEN_VMWARE		0x15adULL
#define	XHC_DEV_VMWARE_1	0x0778ULL
#define	XHC_DEV_VMWARE_2	0x0779ULL

#define XHC_VEN_ASMEDIA		0x1b21ULL
#define XHC_DEV_ASM1042		0x1042ULL
#define XHC_DEV_ASM1042A	0x1142ULL
#define XHC_DEV_ASM1143		0x1343ULL
#define XHC_DEV_ASM3242		0x3242ULL

static struct pciid ids[] = {
	{ XHC_VEN_INTEL, XHC_DEV_COMET_LAKE_LP },
	{ XHC_VEN_INTEL, XHC_DEV_COMET_LAKE },
	{ XHC_VEN_INTEL, XHC_DEV_N2000 },
	{ XHC_VEN_INTEL, XHC_DEV_C3000 },
	{ XHC_VEN_INTEL, XHC_DEV_C210 },
	{ XHC_VEN_INTEL, XHC_DEV_E8000 },
	{ XHC_VEN_INTEL, XHC_DEV_PUMA },
	{ XHC_VEN_INTEL, XHC_DEV_CELERON },
	{ XHC_VEN_INTEL, XHC_DEV_ICE_LAKE },
	{ XHC_VEN_INTEL, XHC_DEV_TIGER_LAKE_H },
	{ XHC_VEN_INTEL, XHC_DEV_N3350 },
	{ XHC_VEN_INTEL, XHC_DEV_C220 },
	{ XHC_VEN_INTEL, XHC_DEV_NINE },
	{ XHC_VEN_INTEL, XHC_DEV_C610 },
	{ XHC_VEN_INTEL, XHC_DEV_EIGHT },
	{ XHC_VEN_INTEL, XHC_DEV_WILDCAT_POINT },
	{ XHC_VEN_INTEL, XHC_DEV_SUNRISE_POINT },
	{ XHC_VEN_INTEL, XHC_DEV_CANNON_POINT },
	{ XHC_VEN_INTEL, XHC_DEV_SILVER },
	{ XHC_VEN_INTEL, XHC_DEV_TIGER_LAKE },
	{ XHC_VEN_INTEL, XHC_DEV_C230 },
	{ XHC_VEN_INTEL, XHC_DEV_C620 },
	{ XHC_VEN_INTEL, XHC_DEV_Z370 },
	{ XHC_VEN_INTEL, XHC_DEV_CANNON_LAKE },

	{ XHC_VEN_AMD, XHC_DEV_KERNCZ },
	{ XHC_VEN_AMD, XHC_DEV_STARSHIP },
	{ XHC_VEN_AMD, XHC_DEV_MATISSE },
	{ XHC_VEN_AMD, XHC_DEV_X399 },
	{ XHC_VEN_AMD, XHC_DEV_X370 },
	{ XHC_VEN_AMD, XHC_DEV_B350 },
	{ XHC_VEN_AMD, XHC_DEV_400 },
	{ XHC_VEN_AMD, XHC_DEV_FCH_1 },
	{ XHC_VEN_AMD, XHC_DEV_FCH_2 },
	{ XHC_VEN_AMD, XHC_DEV_FCH_3 },

	{ XHC_VEN_VMWARE, XHC_DEV_VMWARE_1 },
	{ XHC_VEN_VMWARE, XHC_DEV_VMWARE_2 },

	{ XHC_VEN_ASMEDIA, XHC_DEV_ASM1042 },
	{ XHC_VEN_ASMEDIA, XHC_DEV_ASM1042A },
	{ XHC_VEN_ASMEDIA, XHC_DEV_ASM1143 },
	{ XHC_VEN_ASMEDIA, XHC_DEV_ASM3242 },
	{ 0, 0 }
};
