DTS=	\
	starfive/jh7110-pine64-star64.dts \
	starfive/jh7110-milkv-mars.dts \
	starfive/jh7110-starfive-visionfive-2-v1.3b.dts \
	starfive/jh7110-starfive-visionfive-2-v1.2a.dts \
	starfive/jh7100-starfive-visionfive-v1.dts \
	starfive/jh7100-beaglev-starlight.dts

.include <bsd.dtb.mk>
